### PR TITLE
Disable addon_securityadvisor.cgi on dnsonly servers

### PR DESCRIPTION
**Pull request by atoomic**
Case CPANEL-18480:

Disable addon_securityadvisor.cgi on dnsonly servers.

### CODE REVIEW

**Comment by bk2204** [comment]
Why wouldn't we let a user run the Security Advisor on a DNSONLY system?  There might be security recommendations that are valuable to them.

**Comment by toddr** [comment]
does it work on dnsonly?

**Comment by bk2204** [comment]
I believe it's at least basically functional, although as @atoomic pointed out, it does flag some things which aren't relevant on DNSONLY systems.  It has historically been able to run on 70 and earlier.

**Comment by toddr** [comment]
@bk2204 Not based on QA testing. you get a blank page on 70.

**Comment by bk2204** [comment]
Okay.  If it doesn't work, then I'm happy with this change.  Feel free to reopen and I'll merge it next time I get a chance.

**Comment by FRooter** [comment]
Loading WHM URI **/cgi/securityadvisor/index.cgi** loads the normal contents and does not produce a blank page on my four DNS Only installations, all running cPanel&WHM version 11.70.0.8 on CentOS 7.4 x86_64 at the time of testing

**Comment by atoomic** [comment]
we need to revert this change

**Pull request merged**
